# Generated by Django 6.0 on 2025-12-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='کد فعالسازی شماره'),
        ),
    ]
