# Generated by Django 6.0 on 2025-12-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0002_alter_user_active_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(unique=True, verbose_name='شماره همراه'),
        ),
    ]
