# Generated by Django 6.0 on 2025-12-13 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.productcategory', verbose_name='والد'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام برند'),
        ),
    ]
