# Generated by Django 6.0 on 2025-12-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_productcategory_parent_alter_productbrand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف'),
        ),
        migrations.AddField(
            model_name='product',
            name='end_discount',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان تخفیف'),
        ),
        migrations.AddField(
            model_name='product',
            name='start_discount',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='قیمت محصول'),
        ),
    ]
