# Generated by Django 6.0 on 2025-12-20 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_productgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecificationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.productcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی مشخصات',
                'verbose_name_plural': 'دسته بندی مشخصات',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('value', models.CharField(max_length=200, verbose_name='ویژگی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.productspecificationgroup', verbose_name='دسته بندی مشخصات')),
            ],
            options={
                'verbose_name': 'شاخص',
                'verbose_name_plural': 'مشخصات',
            },
        ),
    ]
